# Generated by Django 4.2 on 2023-06-18 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vebschet', '0002_alter_userprofile_counter_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='counter_number',
            new_name='counter',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='plot_number',
            new_name='field',
        ),
    ]
