# Generated by Django 4.2 on 2023-06-19 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vebschet', '0004_meterreading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterreading',
            name='date_submitted',
        ),
        migrations.RemoveField(
            model_name='meterreading',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='meterreading',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='reading',
            field=models.FloatField(),
        ),
    ]
