# Generated by Django 4.2 on 2023-06-19 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vebschet', '0005_remove_meterreading_date_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vebschet.userprofile'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='reading',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
