# Generated by Django 4.2 on 2023-06-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vebschet', '0006_meterreading_counter_alter_meterreading_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='howireceive',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
