# Generated by Django 4.2 on 2023-06-24 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vebschet', '0008_electricitycost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElectricityCost',
        ),
    ]
