# Generated by Django 4.2 on 2023-06-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vebschet', '0010_electricityprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricityprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
